# Generated by Django 4.1.7 on 2023-04-06 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price', models.IntegerField(verbose_name='Ціна')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='img/products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='GlassCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Чоловічі'), ('W', 'Жіночі'), ('U', 'Унісекс')], max_length=1, verbose_name='Стать')),
                ('glass_form', models.CharField(choices=[('С', 'Кругла'), ('N', 'Нестандартна'), ('S', 'Квадратна'), ('C', 'Котяче око'), ('P', 'Прямокутна')], max_length=1, verbose_name='Форма окулярів')),
                ('glass_color', models.CharField(choices=[('#FFFFFF', 'білий'), ('#00BFFF', 'блакитний'), ('#800000', 'бордовий'), ('#FFFF00', 'жовтий'), ('#008000', 'зелений'), ('#FFD700', 'золотий'), ('#8B4513', 'карі'), ('#964B00', 'коричневий'), ('#FFA500', 'помаранчевий'), ('#######', 'прозорий'), ('#FFC0CB', 'рожевий'), ('#808080', 'сірий'), ('#0000FF', 'синій'), ('#00008B', 'темно-синій'), ('#800080', 'фіолетовий'), ('#000000', 'чорний')], max_length=7, verbose_name='Колір окулярів')),
                ('lens_color', models.CharField(choices=[('#FFFFFF', 'білий'), ('#00BFFF', 'блакитний'), ('#800000', 'бордовий'), ('#FFFF00', 'жовтий'), ('#008000', 'зелений'), ('#FFD700', 'золотий'), ('#8B4513', 'карі'), ('#964B00', 'коричневий'), ('#FFA500', 'помаранчевий'), ('#######', 'прозорий'), ('#FFC0CB', 'рожевий'), ('#808080', 'сірий'), ('#0000FF', 'синій'), ('#00008B', 'темно-синій'), ('#800080', 'фіолетовий'), ('#000000', 'чорний')], max_length=7, verbose_name='Колір лінз')),
                ('glass_material', models.CharField(choices=[('metal', 'метал'), ('titanium', 'титан'), ('stainless steel', 'нержавіюча сталь'), ('plastic', 'пластик'), ('wood', 'дерево')], max_length=15, verbose_name='Матеріал оправи')),
                ('size_eyepiece', models.PositiveIntegerField(verbose_name='Розмір окуляра')),
                ('size_earring', models.PositiveIntegerField(verbose_name='Розмір завушника')),
                ('size_bridge', models.PositiveIntegerField(verbose_name='Розмір мостика')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='product.product')),
            ],
        ),
    ]
