# Generated by Django 4.1.7 on 2023-04-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AddField(
            model_name='glasscharacteristics',
            name='category',
            field=models.CharField(blank=True, choices=[('Сонцезахисні окуляри', 'Сонцезахисні окуляри'), ('Оправи', 'Оправи')], max_length=20, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='glasscharacteristics',
            name='gender',
            field=models.CharField(choices=[('Чоловічі', 'Чоловічі'), ('Жіночі', 'Жіночі'), ('Унісекс', 'Унісекс'), ('Дитячі', 'Дитячі')], max_length=10, verbose_name='Стать'),
        ),
        migrations.AlterField(
            model_name='glasscharacteristics',
            name='glass_color',
            field=models.CharField(choices=[('Білий', 'Білий'), ('Блакитний', 'Блакитний'), ('Бордовий', 'Бордовий'), ('Жовтий', 'Жовтий'), ('Зелений', 'Зелений'), ('Золотий', 'Золотий'), ('Карі', 'Карі'), ('Коричневий', 'Коричневий'), ('Помаранчевий', 'Помаранчевий'), ('Прозорий', 'Прозорий'), ('Рожевий', 'Рожевий'), ('Сірий', 'Сірий'), ('Синій', 'Синій'), ('Темно-синій', 'Темно-синій'), ('Фіолетовий', 'Фіолетовий'), ('Чорний', 'Чорний')], max_length=20, verbose_name='Колір окулярів'),
        ),
        migrations.AlterField(
            model_name='glasscharacteristics',
            name='glass_form',
            field=models.CharField(choices=[('Кругла', 'Кругла'), ('Нестандартна', 'Нестандартна'), ('Квадратна', 'Квадратна'), ('Котяче око', 'Котяче око'), ('Прямокутна', 'Прямокутна')], max_length=15, verbose_name='Форма окулярів'),
        ),
        migrations.AlterField(
            model_name='glasscharacteristics',
            name='glass_material',
            field=models.CharField(choices=[('Метал', 'Метал'), ('Титан', 'Титан'), ('Нержавіюча сталь', 'Нержавіюча сталь'), ('Пластик', 'Пластик'), ('Дерево', 'Дерево')], max_length=20, verbose_name='Матеріал оправи'),
        ),
        migrations.AlterField(
            model_name='glasscharacteristics',
            name='lens_color',
            field=models.CharField(blank=True, choices=[('Білий', 'Білий'), ('Блакитний', 'Блакитний'), ('Бордовий', 'Бордовий'), ('Жовтий', 'Жовтий'), ('Зелений', 'Зелений'), ('Золотий', 'Золотий'), ('Карі', 'Карі'), ('Коричневий', 'Коричневий'), ('Помаранчевий', 'Помаранчевий'), ('Прозорий', 'Прозорий'), ('Рожевий', 'Рожевий'), ('Сірий', 'Сірий'), ('Синій', 'Синій'), ('Темно-синій', 'Темно-синій'), ('Фіолетовий', 'Фіолетовий'), ('Чорний', 'Чорний')], max_length=15, null=True, verbose_name='Колір лінз'),
        ),
    ]
